# Generated by Django 3.1.2 on 2020-12-07 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(editable=False)),
                ('last_update', models.DateTimeField()),
                ('cost', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['perk', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('created', models.DateTimeField(editable=False)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Forge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(editable=False)),
                ('last_update', models.DateTimeField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='imgs/forge_banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(editable=False)),
                ('last_update', models.DateTimeField()),
                ('cost', models.PositiveIntegerField()),
                ('source_old', models.CharField(max_length=200)),
                ('url_wikipedia', models.URLField(blank=True, null=True)),
                ('url_youtube', models.URLField(blank=True, null=True)),
                ('background', models.ImageField(blank=True, null=True, upload_to='imgs/perk_backgrounds/')),
                ('original', models.TextField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf_core.domain')),
                ('last_editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prereq_addons', models.ManyToManyField(blank=True, related_name='required_for_perks', to='cf_core.Addon')),
                ('prereq_perks', models.ManyToManyField(blank=True, related_name='required_for_perks', to='cf_core.Perk')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(editable=False)),
                ('url_wikipedia', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(editable=False)),
                ('xml', models.TextField()),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('perk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_versions', to='cf_core.perk')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(editable=False)),
                ('last_update', models.DateTimeField()),
                ('forge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='cf_core.forge')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_update'],
            },
        ),
        migrations.AddField(
            model_name='perk',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cf_core.source'),
        ),
        migrations.AddField(
            model_name='forge',
            name='perks',
            field=models.ManyToManyField(blank=True, related_name='forges', to='cf_core.Perk'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.PositiveIntegerField()),
                ('locked', models.BooleanField()),
                ('number', models.PositiveIntegerField(default=0)),
                ('addons', models.ManyToManyField(blank=True, to='cf_core.Addon')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf_core.domain')),
                ('perk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf_core.perk')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cf_core.run')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='addon',
            name='perk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cf_core.perk'),
        ),
        migrations.AddField(
            model_name='addon',
            name='prereq_addons',
            field=models.ManyToManyField(blank=True, related_name='required_for_addons', to='cf_core.Addon'),
        ),
        migrations.AddField(
            model_name='addon',
            name='prereq_perks',
            field=models.ManyToManyField(blank=True, related_name='required_for_addons', to='cf_core.Perk'),
        ),
    ]
