# Generated by Django 3.1.7 on 2021-02-25 19:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cf_core', '0004_auto_20210208_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addon',
            options={'ordering': ['perk', 'name']},
        ),
        migrations.AlterModelOptions(
            name='perk',
            options={'ordering': ['domain', 'name']},
        ),
        migrations.AlterField(
            model_name='forge',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='background',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
