# Generated by Django 3.1.2 on 2020-12-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cf_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perk',
            name='source_old',
        ),
    ]
