# Generated by Django 3.1.2 on 2020-12-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_core', '0002_remove_perk_source_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='original',
            field=models.TextField(blank=True, null=True),
        ),
    ]
